### ISSUE TITLE
miniprogram-request 库 get 的返回值与泛型定义不一致

### ISSUE THREAD

**Issue by mutoe** [NewFuture/miniprogram-network#16]
### 版本
`miniprogram-request`: `4.5.3`

### 问题
根据文档中说明的返回值泛型
![图片](https://user-images.githubusercontent.com/9391981/58605896-1643eb80-82cc-11e9-8526-3d84c630cd00.png)

在实际的使用中 `REQUEST.get<Item[]>()` 会返回 `Promise<response>`
而 `response === { data: Item[], ... }`

### 期望
`REQUEST.get<Item[]>()` 直接返回 `Promise<Item[]>`

或 文档中泛型定义为 `REQUEST.get<{data: Item[]}>()` (*I don't think this is good.*)

**Comment by NewFuture** [comment]
```ts
import {REQUEST,transformRequestResponseOkData} from 'miniprogram-network';
//import {REQUEST,transformRequestResponseOkData} from 'miniprogram-request';
REQUEST.Defaults.transformResponse = transformRequestResponseOkData;
```
加上这个转换，就会自动提取data

默认不对res进行任何处理，
这个`transformRequestResponseOkData`会对数据进行200进行处理

**Comment by mutoe** [comment]
@NewFuture  太棒了!
抱歉我没看network下的相关说明, 我稍后提交一个PR在request下补充
