### ISSUE TITLE
全局拦截

### ISSUE THREAD

**Issue by jechtliu** [NewFuture/miniprogram-network#20]
能否提供一下全局拦截的例子？

**Comment by NewFuture** [comment]
为所有的默认请求注入一个认证的 Authorization

```js
import { REQUEST, transformRequestSendDefault } from "miniprogram-network";

// 同步方式
REQUEST.Defaults.transformSend = (options) => {
    options.headers["Authorization"] = `brearer ${getAuthToken()}`; // 更安全的做法应该检查一下 headers 是否存在
    return transformRequestSendDefault(options);
};

// 异步方式 (promise 也可) 
REQUEST.Defaults.transformSend = async (options) => {
    const token = await getAuthTokenPromise(); // 异步方法
    options.headers["Authorization"] = `brearer ${token}`;
    return transformRequestSendDefault(options);
};
```

**Comment by shellRaining** [comment]
> // 异步方式 (promise 也可) 
> REQUEST.Defaults.transformSend = async (options) => {
>     const token = await getAuthTokenPromise(); // 异步方法
>     options.headers["Authorization"] = `brearer ${token}`;
>     return transformRequestSendDefault(options);
> };
> ```

我在文档中没有找到 `transformSend` 请问是不是可以用 `transformRequest` 替代了呢？

**Comment by NewFuture** [comment]
@shellRaining  https://github.com/NewFuture/miniprogram-network/tree/master/request#options
只有`transformSend` and `transformResponse`

TransformRequest 在哪看到的？
