### ISSUE TITLE
不兼容wx.request的api？

### ISSUE THREAD

**Issue by ijandc** [NewFuture/miniprogram-network#23]
```
 const {
     request
 } = require('miniprogram-network');

request({ 
    url: Api.queryConfigurationStatus,
    data: params,
    method: "POST",
    success: function (res) {
            //回调不走
    }
})
```
请求能够成功发出，但是回调`success`不进，`fail`和`complate`也不进，
换成`wx.request`立马就好了，
这是不兼容`wx.request`的`api`吗？

**Comment by ijandc** [comment]
能提供个兼容版本吗？或者我PR一下

**Comment by NewFuture** [comment]
回调使用promise的`then`, `catch`, `finally` 代替了。

这样使用的场景/目的是什么？

**Comment by ijandc** [comment]
我们项目里面原来用的是wx.request，不想一个个去改了@NewFuture

**Comment by NewFuture** [comment]
@ijandc 
这可以两个同时使用的，之前的也不用改

**Comment by ijandc** [comment]
那算了，还是不用了吧




| |
ijandc
邮箱：ijandc@163.com
|

Signature is customized by Netease Mail Master

在2019年07月26日 04:57，New Future 写道：

@ijandc
这可以两个同时使用的，之前的也不用改
