### ISSUE TITLE
请求超时时捕获异常的 errMsg 优化

### ISSUE THREAD

**Issue by lixiaofeng666** [NewFuture/miniprogram-network#30]
超时返回的数据 { errMsg: "request:fail " }, fail 后面多了个空格, 费了点眼力才看出来 :(

**Comment by NewFuture** [comment]
超时的信息正常情况是`request:fail timeout...`这样的(自定义超时后面会写上超时时间)

这个后面空格是什么情况出现的?

**Comment by lixiaofeng666** [comment]
出现情况:

**Comment by NewFuture** [comment]
@lixiaofeng666 ?

**Comment by NewFuture** [comment]
嗯，这个应该是开发工具的行为，底层库不应该做处理
