### ISSUE TITLE
http2支持

### ISSUE THREAD

**Issue by superlbr** [NewFuture/miniprogram-network#51]
根据最新的[wx.request文档](https://developers.weixin.qq.com/miniprogram/dev/api/network/request/wx.request.html)，
新增enableHttp2、enableQuic、enableHttpDNS等配置

**Comment by NewFuture** [comment]
#52

**Comment by superlbr** [comment]
npm能更新下吗，还有readme，谢谢

**Comment by NewFuture** [comment]
@superlbr 试一下这个 5.3.0-alpha.0

**Comment by superlbr** [comment]
妥
